# Activity
From Quotes, extract all quotes & authors from all pages with the life tag

### Scrape Multiple page

In [36]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [8]:
# url = f"https://quotes.toscrape.com/page/1/"
page_count = 1
while True:
    url = f"https://quotes.toscrape.com/page/{page_count}/"
    res = requests.get(url)
    soup = BeautifulSoup(res.text,"lxml")
    quotes = soup.select("div.quote")
    if not quotes:
        print("no Valid pages anymore..")
        break
    with open(f"Scraped_data/quotes{page_count}.html","w",encoding = "utf-8") as f:
        f.write(res.text)
        print(f"dw data from page {page_count}")
    page_count += 1

dw data from page 1
dw data from page 2
dw data from page 3
dw data from page 4
dw data from page 5
dw data from page 6
dw data from page 7
dw data from page 8
dw data from page 9
dw data from page 10
no Valid pages anymore..

# Activity - 2

### get use ful info from scrapped data

In [17]:
with open("Scraped_data/quotes1.html","r",encoding = "utf-8") as f:
    html_content = f.read()
soup = BeautifulSoup(html_content,"lxml")
all_quotes = soup.select("div.quote")
print(all_quotes)

[<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
<a class="tag" href="/tag/change/page/1/">change</a>
<a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
<a class="tag" href="/tag/thinking/page/1/">thinking</a>
<a class="tag" href="/tag/world/page/1/">world</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
<span>by <small class="author" itemprop="author">J.K. Rowling</small>
<a href="/author/J-K-Rowling">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
<a class="tag" href="/tag/abilities/page/1/">abilities</a>
<a class="tag" href="/tag/choices/page/1/">choices</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
<a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
<a class="tag" href="/tag/life/page/1/">life</a>
<a class="tag" href="/tag/live/page/1/">live</a>
<a class="tag" href="/tag/miracle/page/1/">miracle</a>
<a class="tag" href="/tag/miracles/page/1/">miracles</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
<span>by <small class="author" itemprop="author">Jane Austen</small>
<a href="/author/Jane-Austen">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
<a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
<a class="tag" href="/tag/books/page/1/">books</a>
<a class="tag" href="/tag/classic/page/1/">classic</a>
<a class="tag" href="/tag/humor/page/1/">humor</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
<span>by <small class="author" itemprop="author">Marilyn Monroe</small>
<a href="/author/Marilyn-Monroe">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
<a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
<a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
<a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
<a class="tag" href="/tag/success/page/1/">success</a>
<a class="tag" href="/tag/value/page/1/">value</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
<span>by <small class="author" itemprop="author">André Gide</small>
<a href="/author/Andre-Gide">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="life,love" itemprop="keywords"/>
<a class="tag" href="/tag/life/page/1/">life</a>
<a class="tag" href="/tag/love/page/1/">love</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
<span>by <small class="author" itemprop="author">Thomas A. Edison</small>
<a href="/author/Thomas-A-Edison">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
<a class="tag" href="/tag/edison/page/1/">edison</a>
<a class="tag" href="/tag/failure/page/1/">failure</a>
<a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
<a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
<span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
<a href="/author/Eleanor-Roosevelt">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
<a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
</div>
</div>, <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
<span>by <small class="author" itemprop="author">Steve Martin</small>
<a href="/author/Steve-Martin">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
<a class="tag" href="/tag/humor/page/1/">humor</a>
<a class="tag" href="/tag/obvious/page/1/">obvious</a>
<a class="tag" href="/tag/simile/page/1/">simile</a>
</div>
</div>]

In [58]:
life_quotes = []
for q in all_quotes:
    all_tags = []
    # print(all_tags)
    for tag in q.select(".tags .tag"):
        all_tags.append(tag.get_text())
        # print(tag.get_text(strip=True))

    if "life" in all_tags:
        text = q.select_one("span.text").get_text()
        author = q.select_one("small.author").get_text()
        life_quotes.append([text,author])
    print(life_quotes)

[]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]
[["“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", 'Jimi Hendrix'], ['“But better to get hurt by the truth than comforted with a lie.”', 'Khaled Hosseini']]

In [56]:
pd.DataFrame(life_quotes,columns=(["Quotes","Author"]))

                                              Quotes           Author
0  “I'm the one that's got to die when it's time ...     Jimi Hendrix
1  “But better to get hurt by the truth than comf...  Khaled Hosseini

In [72]:
page_count = 1
life_quotes1 = []
while True:
    with open(f"Scraped_data/quotes{page_count}.html","r",encoding = "utf-8") as f:
        html_content = f.read()
        print(page_count)
    soup = BeautifulSoup(html_content,"lxml")
    all_quotes1 = soup.select("div.quote")
    # print(all_quotes1)
    # life_quotes1 = []
    for q in all_quotes1:
        all_tags = []
        # print(all_tags)
        for tag in q.select(".tags .tag"):
            all_tags.append(tag.get_text())
            # print(tag.get_text(strip=True))
        if "life" in all_tags:
            text = q.select_one("span.text").get_text()
            author = q.select_one("small.author").get_text()
            life_quotes1.append([text,author])
        
    if page_count == 10:
        break
    page_count +=1

1
2
3
4
5
6
7
8
9
10

In [73]:
pd.DataFrame(life_quotes1,columns=(["Quotes","Author"]))

                                               Quotes               Author
0   “There are only two ways to live your life. On...      Albert Einstein
1   “It is better to be hated for what you are tha...           André Gide
2   “This life is what you make it. No matter what...       Marilyn Monroe
3   “I may not have gone where I intended to go, b...        Douglas Adams
4   “Good friends, good books, and a sleepy consci...           Mark Twain
5   “Life is what happens to us while we are makin...       Allen Saunders
6   “Today you are You, that is truer than true. T...            Dr. Seuss
7   “Life is like riding a bicycle. To keep your b...      Albert Einstein
8   “Life isn't about finding yourself. Life is ab...  George Bernard Shaw
9   “Finish each day and be done with it. You have...  Ralph Waldo Emerson
10  “The fear of death follows from the fear of li...           Mark Twain
11  “I'm the one that's got to die when it's time ...         Jimi Hendrix
12  “But better to get hurt by the truth than comf...      Khaled Hosseini

# Ai Response Better Code (Activity 2)

In [77]:

import pandas as pd
from bs4 import BeautifulSoup

page_count = 1
life_quotes1 = []

while True:
    try:
        with open(f"Scraped_data/quotes{page_count}.html", "r", encoding="utf-8") as f:
            html_content = f.read()
    except FileNotFoundError:
        break  # stop if file doesn't exist
    
    soup = BeautifulSoup(html_content, "lxml")
    all_quotes1 = soup.select("div.quote")
    
    if not all_quotes1:
        break  # stop if no quotes found
    
    for q in all_quotes1:
        tags = [tag.get_text() for tag in q.select(".tags .tag")]
        if "life" in tags:
            text = q.select_one("span.text").get_text()
            author = q.select_one("small.author").get_text()
            life_quotes1.append([text, author])
    
    page_count += 1

df = pd.DataFrame(life_quotes1, columns=["Quotes", "Author"])
df

                                               Quotes               Author
0   “There are only two ways to live your life. On...      Albert Einstein
1   “It is better to be hated for what you are tha...           André Gide
2   “This life is what you make it. No matter what...       Marilyn Monroe
3   “I may not have gone where I intended to go, b...        Douglas Adams
4   “Good friends, good books, and a sleepy consci...           Mark Twain
5   “Life is what happens to us while we are makin...       Allen Saunders
6   “Today you are You, that is truer than true. T...            Dr. Seuss
7   “Life is like riding a bicycle. To keep your b...      Albert Einstein
8   “Life isn't about finding yourself. Life is ab...  George Bernard Shaw
9   “Finish each day and be done with it. You have...  Ralph Waldo Emerson
10  “The fear of death follows from the fear of li...           Mark Twain
11  “I'm the one that's got to die when it's time ...         Jimi Hendrix
12  “But better to get hurt by the truth than comf...      Khaled Hosseini