# Eda 
Exploratory data analysis

1. load and structure data
2. clean data
3. statistical summary
4. visualization 

pandas --> Series, DataFrame

In [4]:
import pandas as pd

In [7]:
info = {
    "name" : ["one","two","three"],
    "cgpa" : [9.5,9,3] 
}
df = pd.DataFrame(info)
df

    name  cgpa
0    one   9.5
1    two   9.0
2  three   3.0

In [19]:
s= pd.Series([23,24,25,26],index=["adam","Eve","Bob","Charlie"])
s

adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64

In [20]:
s= pd.Series([23,24,25,26],index=list("abcd"))
s

a    23
b    24
c    25
d    26
dtype: int64

# DataFrame

In [26]:
info = {
    "name" : ["one","two","three"],
    "Age" : [45,33,33],
    "cgpa" : [9.5,9,3] 
}
df = pd.DataFrame(info)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

    name  Age  cgpa
0    one   45   9.5
1    two   33   9.0
2  three   33   3.0

pd.read_csv()
& 
pd.read_json()
& 
pd.read_excel()
&
pd.read_sql()

# Methods

In [51]:
print( "head",df.head(1),'\n')
print( "tail",df.tail(1),'\n')
print( "sample",df.sample(),'\n')  # random row print
print( "info",df.info(),'\n')
print( "head",df.head(),'\n')
print( "shape",df.shape,'\n')   # print shape of dictory
print( "describe",df.describe(),'\n')
print( "columns",df.columns,'\n')
print( "nunique",df.nunique(),'\n')

head   name  Age  cgpa
0  one   45   9.5

tail     name  Age  cgpa
2  three   33   3.0

sample   name  Age  cgpa
0  one   45   9.5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   Age     3 non-null      int64
 2   cgpa    3 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes
info None

head     name  Age  cgpa
0    one   45   9.5
1    two   33   9.0
2  three   33   3.0

shape (3, 3)

describe              Age      cgpa
count   3.000000  3.000000
mean   37.000000  7.166667
std     6.928203  3.617089
min    33.000000  3.000000
25%    33.000000  6.000000
50%    33.000000  9.000000
75%    39.000000  9.250000
max    45.000000  9.500000

columns Index(['name', 'Age', 'cgpa'], dtype='object')

nunique name    3
Age     2
cgpa    3
dtype: int64

# Kaggle Dataset

In [79]:
data = pd.read_csv("globalAirQuality.csv")
data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [58]:
data[["city","aqi"]]
data.loc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [62]:
print(df.loc[0:2],"\n\n")   # in loc last index is not excluded
print(df.iloc[0:2])        # in iloc last index is excluded

    name  Age  cgpa
0    one   45   9.5
1    two   33   9.0
2  three   33   3.0


  name  Age  cgpa
0  one   45   9.5
1  two   33   9.0

In [63]:
data.at[0,"city"]

'New York'

In [64]:
data.iat[0,2]

'New York'

In [73]:
# Filtering  of Data
data[(data["aqi"] > 200) & (data["temperature"] > 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17458,2025-11-12 04:25:17.554219,FI,Helsinki,60.17,24.938,14.329,51.173,81.111,7.725,61.16,1.383,202,34.42,26.061,3.771

#  Query

In [77]:
data.query("aqi > 200")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
745,2025-11-05 19:25:17.554219,GB,London,51.507,-0.128,107.144,43.819,13.389,4.601,21.680,0.890,214,19.055,66.245,1.637
8941,2025-11-17 07:25:17.554219,JP,Osaka,34.694,135.502,102.142,95.204,41.688,7.806,28.951,0.753,204,15.277,76.131,4.586
12956,2025-11-19 14:25:17.554219,NZ,Auckland,-36.848,174.763,44.824,66.657,90.019,3.637,41.311,0.849,225,14.872,63.319,0.958
14555,2025-11-11 05:25:17.554219,PH,Manila,14.600,120.984,103.023,66.678,43.284,2.167,48.250,0.849,206,11.027,63.522,7.635
17458,2025-11-12 04:25:17.554219,FI,Helsinki,60.170,24.938,14.329,51.173,81.111,7.725,61.160,1.383,202,34.420,26.061,3.771
17529,2025-11-15 03:25:17.554219,FI,Helsinki,60.170,24.938,115.683,81.714,54.764,6.687,39.552,0.685,231,25.795,87.839,6.705
17815,2025-11-12 01:25:17.554219,CH,Zurich,47.377,8.542,54.805,39.178,81.406,10.241,46.579,0.498,203,20.883,70.201,3.500

# Cleaning Data

isnull() / isna()
isnull().sum()
dropna()
fillna(value)
ffill()
bfill()

In [78]:
data.dropna()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [85]:
data.ffill()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

## Data Cleaning
# Cleaning Duplicate values

In [98]:
data[["country","city"]].duplicated()

0        False
1         True
2         True
3         True
4         True
         ...
17995     True
17996     True
17997     True
17998     True
17999     True
Length: 18000, dtype: bool

In [100]:
data2 = data.copy()
data["country"].drop_duplicates(inplace = True)

In [101]:
data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

# Handle Data types & date-time

In [124]:
print(data.dtypes,'\n')
data2 = data.copy()
data2 = data2.fillna(0)
data2['pm25'] = data2["pm25"].astype('int64')
data2.dtypes

timestamp       object
country         object
city            object
latitude       float64
longitude      float64
pm25           float64
pm10           float64
no2            float64
so2            float64
o3             float64
co             float64
aqi              int64
temperature    float64
humidity       float64
wind_speed     float64
dtype: object

timestamp       object
country         object
city            object
latitude       float64
longitude      float64
pm25             int64
pm10           float64
no2            float64
so2            float64
o3             float64
co             float64
aqi              int64
temperature    float64
humidity       float64
wind_speed     float64
dtype: object

In [117]:
data['pm25'].dtype

dtype('float64')

# Handle Strings

In [128]:
data['city'].str.lower()

0        new york
1        new york
2        new york
3        new york
4        new york
           ...
17995      zurich
17996      zurich
17997      zurich
17998      zurich
17999      zurich
Name: city, Length: 18000, dtype: object

In [129]:
data['city'].str.upper()

0        NEW YORK
1        NEW YORK
2        NEW YORK
3        NEW YORK
4        NEW YORK
           ...
17995      ZURICH
17996      ZURICH
17997      ZURICH
17998      ZURICH
17999      ZURICH
Name: city, Length: 18000, dtype: object

In [130]:
data['city'].str.capitalize()

0        New york
1        New york
2        New york
3        New york
4        New york
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [132]:
data['city'].str.split(" ")

0        [New, York]
1        [New, York]
2        [New, York]
3        [New, York]
4        [New, York]
            ...
17995       [Zurich]
17996       [Zurich]
17997       [Zurich]
17998       [Zurich]
17999       [Zurich]
Name: city, Length: 18000, dtype: object

In [138]:
data['city'].str.contains("india",case = False)

0        False
1        False
2        False
3        False
4        False
         ...
17995    False
17996    False
17997    False
17998    False
17999    False
Name: city, Length: 18000, dtype: bool