# Regression

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.datasets import make_regression
# from sklearn import

In [48]:
# generate data
X ,y = make_regression(
    n_samples = 1000,
    n_features = 10,
    noise = 20,
    random_state = 42
)
# Convert to DataFrame
df = pd.DataFrame(X, columns=[f"feature_{i}" for i in range(X.shape[1])])
df["target"] = y

df.head()

   feature_0  feature_1  feature_2  feature_3  feature_4  ...  feature_6  feature_7  feature_8  feature_9      target
0   1.575876   0.891863  -0.726774  -0.047799  -0.657035  ...  -0.877617   0.994558  -0.299696  -0.761760  -55.195740
1   0.535459   1.266661  -1.779875   1.209010  -0.113158  ...   1.064171  -0.555273   0.741320  -0.987523   82.544625
2  -0.686279   0.157128   0.145836  -1.432671  -0.666849  ...   0.585299   0.197917  -0.404362  -0.607472 -100.147756
3   0.925282   0.395914   0.676357   0.168651   1.574147  ...  -0.037687  -0.345907   0.895796  -0.837381   62.183807
4  -0.558922   1.073632   1.565524   0.377212   0.132970  ...  -0.065750  -0.700121  -1.523187   1.195047  158.811856

[5 rows x 11 columns]

In [49]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

# Gradient Boosting

In [50]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(
    learning_rate = 0.1,
    n_estimators = 200,
    max_depth = 3,
    random_state = 42 
)

In [51]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor(n_estimators=200, random_state=42)

In [52]:
y_pred = gbr.predict(X_test)
print(r2_score(y_pred, y_test))

0.8983363767580576

# Classifier

In [22]:
from sklearn.datasets import make_classification

In [26]:
X, y = make_classification(
    n_samples = 1000,
    n_features = 20,
    n_informative=  10, 
    random_state = 42
)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [29]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(
    learning_rate = 0.1,
    n_estimators = 150,
    max_depth = 3,
    random_state = 42
)

In [30]:
from sklearn.metrics import accuracy_score
gbc.fit(X_train, y_train)

GradientBoostingClassifier(n_estimators=150, random_state=42)

In [31]:
y_pred = gbc.predict(X_test)
print(accuracy_score(y_pred, y_test))

0.925

   feature_0  feature_1  feature_2  feature_3  feature_4  ...  feature_6  feature_7  feature_8  feature_9      target
0   1.575876   0.891863  -0.726774  -0.047799  -0.657035  ...  -0.877617   0.994558  -0.299696  -0.761760  -55.195740
1   0.535459   1.266661  -1.779875   1.209010  -0.113158  ...   1.064171  -0.555273   0.741320  -0.987523   82.544625
2  -0.686279   0.157128   0.145836  -1.432671  -0.666849  ...   0.585299   0.197917  -0.404362  -0.607472 -100.147756
3   0.925282   0.395914   0.676357   0.168651   1.574147  ...  -0.037687  -0.345907   0.895796  -0.837381   62.183807
4  -0.558922   1.073632   1.565524   0.377212   0.132970  ...  -0.065750  -0.700121  -1.523187   1.195047  158.811856

[5 rows x 11 columns]